### ISSUE TITLE
Improve selection feature - finer grain, and ability to unselect individual objects in a collection set

### ISSUE THREAD

**Issue by belzecue** [mbrlabs/Lorien#12] opened 2021-06-04 05:58 UTC
Tested on Linux Ubuntu 20.04.

**Feature/enhancement description:**
Allow for more fine-grain selection of objects.  We should be able to box-select part of an object and have that object selected.  For example, here I box-select the end of an arrow (arrow head and arrow line) but upon mouse release they are not selected.

![Screenshot at 2021-06-04 13-45-05](https://user-images.githubusercontent.com/1931303/120751926-6305d100-c53b-11eb-8a3f-a884b3228df3.png)

The only way to select that arrow is to bounding-box select the entire object, which includes other objects I don't want to select...

![Screenshot at 2021-06-04 13-50-38](https://user-images.githubusercontent.com/1931303/120752200-e1627300-c53b-11eb-99af-075320beff3e.png)

Once objects have been selected, there seems to be no way to unselect individual objects in that collection.  If I shift+mouse-box-select one selected object in a collection of selected objects, I would expect that one object to be unselected.

![Screenshot at 2021-06-04 13-56-59](https://user-images.githubusercontent.com/1931303/120752763-c47a6f80-c53c-11eb-96fa-91e3f521ba9a.png)

**Comment by mbrlabs** [comment] 2021-06-04 07:39
Agree to your first request but that has to wait a bit. See: #7

Deselecting individual strokes should definitely be implemented. It should be pretty easy to do that. Strokes are selected by adding them to a `selected_strokes` group. So they would just have to be removed from that group if they get selected again.

**Comment by mbrlabs** [comment] 2021-06-06 11:33
I just implemented partial deselection of strokes when holding down shift in d21130c4d6057fe14df19a457f5c11411b221258.

Closing this issue now, since the other issue you requested is a duplicate of #7.

**Closed by mbrlabs** 2021-06-06 11:33 UTC
Labels: enhancement
