### ISSUE TITLE
Line thickness inconsistencies in Windows

### ISSUE THREAD

**Issue by gitkeerthi** [mbrlabs/Lorien#252] opened 2023-11-13 04:28 UTC
**Lorien version:**
0.6.0

**OS/device including version:**
Windows 11

**Issue description:**
Line thickness of objects (rectangle, circle, etc.) does not match that of handwritten text for the same brush size. Only observed in Windows. Looks good in Linux. 

**Steps to reproduce:**
See screenshot
![Screenshot 2023-11-13 095453](https://github.com/mbrlabs/Lorien/assets/25875235/6fd16e78-9205-4a38-b436-6b7a7951bb64)

**Comment by tafode** [comment] 2024-02-27 22:30
I tried to find the issue. I think the problem is, that the pressure for Circle/Rectangle is set as a constant to 0.5. This would mean the line is always half the size of the brush, but additional the interpolate function is called with 0.5 which looks up the pressure inside a pressure curve which decreases the size again. (e.g. CircleTool.gd line 55 `pressure = pressure_curve.interpolate(pressure)`. 

In my opinion setting the constant to 1 would solve the problem.
![Lorien](https://github.com/mbrlabs/Lorien/assets/17379814/d5bf534a-641f-4879-a3a0-a618bd6292e0)

I don't know how or why it should work on Linux and I have at the moment no possibility to check it on Linux.

**Comment by mbrlabs** [comment] 2024-03-18 11:56
Fixed with #263

**Closed by mbrlabs** 2024-03-18 11:56 UTC
Labels: bug
