### ISSUE TITLE
Shortcut collisions from missing control key

### ISSUE THREAD

**Issue by Gurchain** [mbrlabs/Lorien#132] opened 2022-06-08 05:13 UTC
**Lorien version:**

be61d304b8db482b4e1ecd4b94c68f3168008455

**OS/device including version:**

Linux (Pop OS 22.04 LTS)

**Issue description:**

The shortcuts for saving a file doesn't require the control key, which negates the selection tool shortcut

other shortcuts don't require control either, such as opening a file 

**Steps to reproduce:**
open the lorien build for be61d304b8db482b4e1ecd4b94c68f3168008455 and press s, the save filedialog will open instead of switching to the select tool

**Comment by mbrlabs** [comment] 2022-06-10 12:15
I can't reproduce this on Windows 11

**Comment by mbrlabs** [comment] 2022-06-10 12:29
Nevermind, this also happens on Windows. My local repo was not up to date.

**Comment by mbrlabs** [comment] 2022-06-10 12:32
Fixed in 02f92778a643544fe9e69225cfc488974548300a

**Closed by mbrlabs** 2022-06-10 12:32 UTC
Labels: bug
