### ISSUE TITLE
a crash occurs when drawing and erasing back and forth

### ISSUE THREAD

**Issue by Memresable** [mbrlabs/Lorien#206] opened 2022-10-09 14:54 UTC
**Lorien version:**
v0.5.0

**OS/device including version:**
Linux kernel version: 5.19.13
Linux distro: Arch
Window System: X11

RAM: DDR3 8GB RAM 1600MHz
CPU: Intel core i7-5500U 3.0GHz (2 cores / 4 threads)
Integrated GPU: Intel HD Graphics 5500 (Mesa)
Dedicated GPU: AMD Radeon R5 M330 (Mesa)

**Issue description:**
when drawing and erasing back and forth (switching between brush and eraser) it crashes and then a segmentation fault error appear in the terminal, it happens on both GPUs

**Steps to reproduce:**
grab a brush, try to draw a line
grab an eraser, erase the thing you drew
repeat until it crashes

what got printed into the terminal:
![Screenshot from 2022-10-09 17-51-30](https://user-images.githubusercontent.com/86978624/194763667-d5a963c9-f9dc-431e-ac45-82ad29557fb2.png)

**Comment by hansemro** [comment] 2022-10-11 01:51
This is likely duplicate of #153, which was fixed after v0.5.0 release. @mbrlabs Maybe create v0.5.1 release with latest changes?

**Comment by mbrlabs** [comment] 2023-08-05 16:15
Yes, duplicate of https://github.com/mbrlabs/Lorien/issues/153. The next release will contain the fix. Thanks for reporting!

**Closed by mbrlabs** 2023-08-05 16:15 UTC
Labels: bug
